apiVersion: apps/v1
kind: Deployment

metadata:
  name: block-game-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: block-game

  template:
    metadata:
      labels:
        app: block-game

    spec:
      containers:
      - name: block-game

        image: bharathgowdao3/block_game:v1.0

        ports:
        - containerPort: 80
